version: '3.8'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./services/backend/.env.test
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    env_file:
      - ./services/backend/.env.db.test
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data_test:
